title: Bartholomule Devlog
description: A game development blog
baseurl: "" # leave this empty for user/organization site
url: "https://bartholomule-dev.github.io" # your site URL

remote_theme: "mmistakes/minimal-mistakes"
plugins:
  - jekyll-remote-theme
  - jekyll-seo-tag
  - jekyll-include-cache
  
# Optional (but recommended)
minimal_mistakes_skin: "dark"
locale: "en-US"

author:
  name: Bartholomule
  avatar: "/assets/images/avatar.png" # optional
  bio: "Developer of TBD, an indie roguelike in progress."

navigation:
  - main
